name = "app"
version = "1.0.0"
target = "javascript"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
lustre = ">= 4.5.0 and < 5.0.0"
lustre_http = ">= 0.5.2 and < 1.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
plinth = ">= 0.4.14 and < 1.0.0"
gleam_http = ">= 3.7.0 and < 4.0.0"
qs = ">= 0.6.0 and < 1.0.0"
rada = ">= 0.4.0 and < 1.0.0"
birl = ">= 1.7.1 and < 2.0.0"
modem = ">= 2.0.1 and < 3.0.0"
gleroglero = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
